apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-screening-api-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-screening-api
  template:
    metadata:
      labels:
        app: ai-screening-api
    spec:
      containers:
      - name: ai-screening-api-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-east1-docker.pkg.dev/aiscreening/ai-screening-api-repo/ai-screening-api-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"